### ISSUE TITLE
Update? :3

### ISSUE THREAD

**Issue by EnderKenji** [thebigsmileXD/MagicWE#10]
Can yah update? :3 

Add more features like
//hsphere
//sphere
//cylinder
etc?

**Comment by thebigsmileXD** [comment]
Oh, wait lol xD

**Comment by EnderKenji** [comment]
Okie :3 Cus Builders really need it :3

If u can do /brush ,then the best <3 xP

**Comment by EnderKenji** [comment]
._.?

**Comment by SalmonGER** [comment]
@EnderKenji I think he updated something to PHP7 lol.

**Comment by thebigsmileXD** [comment]
I thought you mean update to PHP7 xD

Requests etc in the todo issue. I call this a duplicate then.

**Comment by Landy005** [comment]
lol kenji

**Comment by EnderKenji** [comment]
lol landy
