### ISSUE TITLE
Won't Work

### ISSUE THREAD

**Issue by ChaostixZix** [thebigsmileXD/MagicWE#11]
I Use //pos1 ,And //pos2 Command, And //set , Then The Plugin Says "Fill Complete"
But, There Is No Change On My World

**Comment by thebigsmileXD** [comment]
Correct usage? Remember you have to use ID's, not //set stone

**Comment by ChaostixZix** [comment]
Yep, I Use //set 5, But Nothing Happen

**Comment by thebigsmileXD** [comment]
May be fixed
