### ISSUE TITLE
._. bug 0.15

### ISSUE THREAD

**Issue by EnderKenji** [thebigsmileXD/MagicWE#12]
![image](https://cloud.githubusercontent.com/assets/15629214/16171532/ba5072da-35a3-11e6-9e0b-2856bc428383.png)
when i do //set

**Comment by SalmonGER** [comment]
Blocks get set. But they are only visible for players after they change world and get back.
Like the server doesn't update the blocks for other clients.

**Comment by EnderKenji** [comment]
is this gonna be fix? like make it update the block like before? :/

**Comment by thebigsmileXD** [comment]
Thats actually currently a client bug. Same like the snow shown client side

**Comment by SalmonGER** [comment]
@thebigsmileXD Oh, thanks for the information!

**Comment by thebigsmileXD** [comment]
:P but i may add sending the chunks to the clients nearby when progress is done. Maybe this will help atleast for some chunks

**Comment by SalmonGER** [comment]
@thebigsmileXD Aww yiss :+1:

**Comment by SalmonGER** [comment]
Fixed in ClearSky now
(Tested)

**Comment by thebigsmileXD** [comment]
not fixed (tested in CS)
