### ISSUE TITLE
how i can load schematic

### ISSUE THREAD

**Issue by FuxonPlayz** [thebigsmileXD/MagicWE#14]
where i supposed to put the schematic file there's no folder

**Comment by thebigsmileXD** [comment]
\*cough plugins/MagicWE/schematics cough\*
//schem [load|paste|export]

**Comment by MajorPlayz** [comment]
lol

**Comment by thebigsmileXD** [comment]
@MajorPlayz Stop spamming "lol" or you get blocked from this repository.
