### ISSUE TITLE
Permission don't works.

### ISSUE THREAD

**Issue by EnderKenji** [thebigsmileXD/MagicWE#15]
I added permission to a person to use WE, but he still can't use WE.
(Hes not op)

**Comment by thebigsmileXD** [comment]
which permission?

**Comment by JoRa22** [comment]
I have been having the same issue. The commands fine for an OP player. But if assign the permissions to another player it does not work. I have tried adding the admin permission "we.commands.admin" as well as adding them individually and they still do not work.

For example: If i type <//pos1> it does not save the first position. Instead, in return I receive a message that says "Usage://pos1"

Can you please provide and update or a fix for this? I would like to have Builders on my server without giving them OP.

Thank you,

**Comment by EnderKenji** [comment]
Hopefully it will be fix soon...

**Comment by Landy005** [comment]
pray

**Comment by thebigsmileXD** [comment]
Checked the permissions, working fine in PHP5. I guess PurePerms is messed up

**Comment by EnderKenji** [comment]
It shouldn't be.. Why others permission works? Should be WE's issue.

**Comment by thebigsmileXD** [comment]
oh my wow.. i see why: the plugin.yml didn't save on the crash once i fixed it.. I am sorry, will be fixed.

**Comment by thebigsmileXD** [comment]
Do you prefer magicwe. or we.

**Comment by EnderKenji** [comment]
we.

**Comment by MajorPlayz** [comment]
@EnderKenji @JoRa22 @Landy005 Nothing like this is happening for me... I have had updated version however I tried old one and still worked! Nevermind!

Btw sorry for bumbping old post :D

**Comment by thebigsmileXD** [comment]
Forgot to close. Fixed in the latest version.
