### ISSUE TITLE
0.16 commands

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [thebigsmileXD/MagicWE#19]
If you use 0.16 (Genisys) you can't perform any commands from worldedit. Another commands from other plugins are working. If you try to perform a command it tells you "Unknown command".

**Comment by thebigsmileXD** [comment]
Core bug. It works just fine on ClearSky, soon also with tab completion. #blamegenisys

**Comment by thebigsmileXD** [comment]
I'll ry to figure out why this happens in genisys. is it "Unknown command" or "Invalid syntax" (second means a client message)

**Comment by Goodstuff4UonYT** [comment]
I remove the permission part and now it works.

**Comment by Tolo0** [comment]
im using MagicWE with genisys 16 and it works fine. but i do know EssentialsPE has been having some unknown commands problems.

**Comment by Tolo0** [comment]
w
![screenshot_20161111-162531](https://cloud.githubusercontent.com/assets/13458191/20222143/0d4a97fe-a82c-11e6-8e2f-87b5904f971a.png)
