### ISSUE TITLE
2.0 Rewrite

### ISSUE THREAD

**Issue by thebigsmileXD** [thebigsmileXD/MagicWE#27]
Cleanup. See #3 #10 
- [ ] Flip (fix)
- [x] Redo (fix)
- [ ] Rotate
- [ ] Sphere (make the code fit)
- [x] HCYL
- [x] CYL
- [ ] //hollow or so
- [x] Add block selection via names (like grass -> 2)
- [ ] //help
- [ ] Give Axe with name on //wand and /toggleeditwand
- [ ] Add /clearhistory
- [ ] Add //size
- [ ] Add //overlay etc., see http://wiki.sk89q.com/wiki/WorldEdit/Reference
- [ ] Add "Asynchronous" operations with max-blocks-per-tick (Will cause rewrite. TODO for v.2)
- [ ] Import Minecraft 1.9+ Structure Block import
- [ ] Add //schem list
- [ ] Better //undo and //redo cache
- [ ] ADD SPHERE!!!!!!!!!

**Comment by Aericio** [comment]
make cyl hycl actually correct. like pc edition. current one is like ew.

**Comment by Apqu** [comment]
Glad you are still updating this plugin, your work is very much appreciated, looking forward to seeing the updates :-)

**Comment by Misteboss** [comment]
Can you uplod asynchronous Update :( ?

**Comment by thebigsmileXD** [comment]
Total reset of this issue. 2.0 will be a new Repo

**Comment by SuperAdam47** [comment]
bukkit worldedit plugin port to pocketmine plugin

**Comment by thebigsmileXD** [comment]
grammar book 6$ shop mall

**Comment by thebigsmileXD** [comment]
Closing as invalid. 2.0 is NOT a cleanup. its a rewrite

**Comment by thebigsmileXD** [comment]
![photo_2017-07-06_13-22-12](https://user-images.githubusercontent.com/8733998/27998475-35ea9244-6510-11e7-88dd-c9969fe83c23.jpg)
