### ISSUE TITLE
World limit = 256 now :)

### ISSUE THREAD

**Issue by Aericio** [thebigsmileXD/MagicWE#28]
(256 i think? idk)
![image](https://cloud.githubusercontent.com/assets/16523741/22095435/c2cb3554-ddb8-11e6-80fd-8053770479d4.png)

**Comment by thebigsmileXD** [comment]
pr plzzz xd

**Comment by Aericio** [comment]
but you cant do world edit above y128 also :)
it lets you select but wont let you //set stuff in :D
