### ISSUE TITLE
With Pocketmine 1.0.0 schem can't be pasted anymore

### ISSUE THREAD

**Issue by Misteboss** [thebigsmileXD/MagicWE#30]
How to reproduce :
-> //schem load test
-> //schem paste test
Result : Succes message "the schem has been pasted..." Nothing is here, the schem hasn't been pasted 
Please fix !

**Comment by Aericio** [comment]
Works fine for me. Make sure you selected a region, then //copy, //schem save blah, //schem load blah, //schem paste blah. If your using 1.0.0, //wand is broken :P (for pmmp at least)
![image](https://cloud.githubusercontent.com/assets/16523741/22134937/f6fd78bc-de6e-11e6-866c-e7981872a356.png)

**Comment by thebigsmileXD** [comment]
Well, fine for me too. I pasted the whole last week, even above 128

**Comment by Misteboss** [comment]
Paste a custom schem doesn't work @Aericio @thebigsmileXD i don't talk of one you have created

**Comment by thebigsmileXD** [comment]
Weird and funny, i pasted a huge maze today (created with Minecraft structure planner) and some other rotated structures exported from mcedit, all fine.

**Comment by thebigsmileXD** [comment]
its not //paste, its //schem paste

**Comment by thebigsmileXD** [comment]
@Aericio btw, //wand works fine for me

**Comment by Misteboss** [comment]
I use //schem paste and nothing happens ^^ and do you have a message when it's finish with time ithas taken ?

**Comment by thebigsmileXD** [comment]
Sure.

**Comment by thebigsmileXD** [comment]
I tag it invalid. it works fine for me.
