### ISSUE TITLE
Where do I put schematics?

### ISSUE THREAD

**Issue by WreckagePE** [thebigsmileXD/MagicWE#34]
Where do I put schematics..?

**Comment by thebigsmileXD** [comment]
plugins/MagicWE/schematics

**Comment by WreckagePE** [comment]
There is no MagicWE folder :/ shall i manually create one?

**Comment by thebigsmileXD** [comment]
... Yes -.-

**Comment by Tolo0** [comment]
😅 i told u dan.

**Comment by WreckagePE** [comment]
When I try to load schematics it says undefined member function getValue() on null

**Comment by thebigsmileXD** [comment]
Corrupted schematic

**Comment by Tolo0** [comment]
if its a schematic from mcpc then use Mcedit
