### ISSUE TITLE
//set only sets air

### ISSUE THREAD

**Issue by Aericio** [thebigsmileXD/MagicWE#4]
//set command only sets air, when I want it to set to grass. Do I need the ID? Or can the name work like WEArt?

**Comment by thebigsmileXD** [comment]
Yes, you eed the ID.

**Comment by Aericio** [comment]
oh okay then :(

**Comment by thebigsmileXD** [comment]
Sure, its in the todo (i think mentioned in the Readme, or in the todo-issue)

**Comment by Aericio** [comment]
k then
