### ISSUE TITLE
Transparent blocks in schematic files not supported

### ISSUE THREAD

**Issue by SOF3** [thebigsmileXD/MagicWE#42]
Add option to paste without replacing with air blocks.

Better to allow setting the source mask as something else too.

https://github.com/sk89q/WorldEdit/blob/1387bd870eb931dbdc8d6285c2303dae378c3aad/worldedit-core/src/main/java/com/sk89q/worldedit/command/ClipboardCommands.java#L105

**Comment by thebigsmileXD** [comment]
Copy/paste air block flags etc are buildt into MagicWE2. MagicWE1 is cancelled. MagicWE2 will not have buildt in schematic loading, it will though be able to create a clipboard from it using a schematic importer by @svilex: https://github.com/svilex/Schematic_Loader
