### ISSUE TITLE
Permission syntax error

### ISSUE THREAD

**Issue by Freeattack-MCPE** [thebigsmileXD/MagicWE#6]
Can you add a PhP 7 version for the plugin and fix the permissions syntax error? it's a great plugin :D

**Comment by thebigsmileXD** [comment]
PHP7 will work except for schematics, as you can read in the r-e-a-d-m-e.

What syntax error? Create issues and provide info instead of letting me guess.

**Comment by SalmonGER** [comment]
@thebigsmileXD He's typing in a command like //pos1 and it just shows him the syntax.
I tried the same commands on my server and on his server. On my they are working fine but on his they only show up the usage/syntax. It's like when you write wrong arguments and the server shows you how the syntax is.

**Comment by thebigsmileXD** [comment]
seems like he tried to add arguments or uses an outdated version

**Comment by SalmonGER** [comment]
@thebigsmileXD I also tried the commands without arguments. But he could have a outdated version. I'll telll him to update and try it again.

**Comment by thebigsmileXD** [comment]
Confirmed as way outdated
