### ISSUE TITLE
Async Feature?

### ISSUE THREAD

**Issue by Aericio** [thebigsmileXD/MagicWE#8]
Add a "Async" feature. There is a feature like this in the PC version of Minecraft called:

Plugin: [Async World Edit / AWE](https://www.spigotmc.org/resources/asyncworldedit.327/)
_Yes, it is a java plugin but its still possible... right?_

It basically splits up the paste or set or cut or whatever to parts so it doesn't do it all at once, which is the possibility of pasting a hella lot more crap into your world besides the limit that we got on MagicWE, because if we copy n paste too much, rip. Watch AWE's tutorial, and you'd get the idea. Maybe it could be an addon plugin, or put into MagicWE's code?

**Comment by thebigsmileXD** [comment]
In progress

**Comment by thebigsmileXD** [comment]
Will not be possible except for schematic loader/exporter. Can not call api functions

**Comment by Aericio** [comment]
cri :(
